name: main
on: push


jobs:
  cypress-test:
    name: Cypress test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run cypress tests with chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome

  deploy-infra:
      needs: cypress-test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.9'
            architecture: 'x64'
        - uses: aws-actions/setup-sam@v1
        - uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - run: sam build
        - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
  
  deploy-site:
    needs: deploy-infra
    runs-on: ubuntu-latest         
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy site because jakejarvis doesn't work
        run: aws s3 sync ./resume-site s3://crc-version-2
