name: main
on: push
env:
  PYTHON_VERSION: 3.12
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:

  test-app:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{env.PYTHON_VERSION }}
      - name: install boto3
        run: pip install boto3
      - name: install simplejson
        run: pip install simplejson
      - name: Test Get Function
        run: cd getFunction && python test.py -v && cd ..
      - name: Test Put Function
        run: cd putFunction && python test.py -v && cd ..

  deploy-infra:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.12'
            architecture: 'x64'
        - uses: aws-actions/setup-sam@v1
        - uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            openai-api-key: ${{ secrets.OPENAI_API_KEY }}
            aws-region: us-east-1
        - run: sam build
        - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides OpenAIApiKey=${{ secrets.OPENAI_API_KEY }}

  deploy-site:
    needs: deploy-infra
    runs-on: ubuntu-latest         
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy site
        run: aws s3 sync ./resume-site s3://ian-cahall-cloud-website

