name: main
on: push
env:
  PYTHON_VERSION: 3.9

jobs:
  test-pp:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install boto3
        run:
          pip3 install boto3
      - name: Install simplejson
        run: pip install simplejson
      - name: test get-function
        run: cd getFunction && python3 test.py -v && cd ..
      - name: test put-function
        run: cd putFunction && python3 test.py -v && cd ..
